feat: custom queue monitoring
laravel/vapor-ui pull request #58
Opened 2021-07-01 23:16 UTC by atymic

Currently in vapor you cannot specify a per queue concurrency, each queue in the environment gets same concurrency. A workaround was suggested by vapor staff to deploy into a separate environment, however the issue is we cannot see queue metrics for the queues outside of the main vapor production environment.

This PR adds the ability to specify custom queues in the config file to monitor in addition to the ones grepped from the config file.

Let me know if any changes required and if not i'll also PR the docs

2021-07-02 16:58 UTC, nunomaduro requested changes

2021-07-02 16:58 UTC, nunomaduro commented on src/Support/Cloud.php
> +        return array_merge(self::guessQueues(), config('vapor-ui.queues'));
```suggestion
        return array_merge(self::guessQueues(), config('vapor-ui.queues', []));
```

2021-07-02 16:58 UTC, nunomaduro commented on config/vapor-ui.php
> +    | Queue names will be automatically guessed from your vapor.yml config but
@taylorotwell You will need to adjust this comment to the Laravel format.

2021-07-03 07:16 UTC, atymic commented
Thanks @nunomaduro, made the change :)

2021-07-05 15:39 UTC, merged